language:
  - swift

osx_image: xcode 12.5

script:
  - xcodebuild -project VoiceMemo/VoiceMemo.xcodeproj -scheme VoiceMemu -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test